version: "3.9"

services:

  de_psql:
    image: postgres:15
    container_name: de_psql
    volumes:
      - ./psql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - data_network

networks:
  data_network:
    driver: bridge
    name: data_network